### ISSUE TITLE
can not support  "swish" layers 

### ISSUE THREAD

**Issue by mingx9527** [azeme1/keras2ncnn#10]

**Comment by azeme1** [comment]
Easy, could you prepare the simple network to test it?

**Comment by mingx9527** [comment]
@azeme1
https://github.com/Ascend-Research/HeadPoseEstimation-WHENet

**Comment by azeme1** [comment]
There is other issue the Lambda can not be converted to the NCNN - it is unclear what is inside this function
![image](https://user-images.githubusercontent.com/7568330/108529112-30fe9500-72e5-11eb-991e-b3cbc94cf966.png)

**Comment by azeme1** [comment]
Do you need only Swish layer or whole model conversion?

**Comment by azeme1** [comment]
Succeed to fix the mode and convert it into the NCNN.

https://www.dropbox.com/sh/8anok3k3jxjj81i/AADWMLad_V0MKs4ySN2mgPPda?dl=0
<dropbox> model_zoo\variouse\issue_00010\WHENet_fixed.h5 - the fixed model
model_zoo\variouse\issue_00010\model_3\ conversion result


The conversion report from run_test should look  like this one 

[issue_000010.txt](https://github.com/azeme1/keras2ncnn/files/6012079/issue_000010.txt)

**Comment by mingx9527** [comment]
@azeme1  Thank you !  

but   model_zoo\variouse\issue_00010\model_3\    *.bin and *.param  is other model,  not whenet .

**Comment by azeme1** [comment]
Sorry. I have copied wrong model.
model_zoo\variouse\issue_00010\model_2\ conversion result

**Comment by azeme1** [comment]
![image](https://user-images.githubusercontent.com/7568330/108746487-702f1f00-754d-11eb-937d-018643cb0d2b.png)

**Comment by azeme1** [comment]
Some optimization was done.
The conversion error
...
Layer - yaw_new inference MAE :: 6.747121688022162e-07 < 1e-05 True Keras::(1, 120) / NCNN::(1, 120)
Layer - pitch_new inference MAE :: 3.3883208061524783e-07 < 1e-05 True Keras::(1, 66) / NCNN::(1, 66)
Layer - roll_new inference MAE :: 3.784274156259926e-07 < 1e-05 True Keras::(1, 66) / NCNN::(1, 66)
Estimated float32 inference memory :: 79 MB

**Comment by azeme1** [comment]
Is the problem solved?
