### ISSUE TITLE
KeyError: 'get_relu6_mapping'

### ISSUE THREAD

**Issue by wangjing60755** [azeme1/keras2ncnn#14]
Can you make it support relu6? It is in common use

**Comment by wangjing60755** [comment]
[Uploading unet_ncnn_model_20210222.zip…]()
tf1.9，win10

**Comment by wangjing60755** [comment]
[unet_ncnn_model_20210222.zip](https://github.com/azeme1/keras2ncnn/files/6022584/unet_ncnn_model_20210222.zip)

tf1.9.

**Comment by azeme1** [comment]
ReLu6 is supported but you normaly should use the ReLU layer with clip parameter. One second I will check the problem

**Comment by azeme1** [comment]
Layer - final_layer inference MAE :: 1.1061612736895654e-09 < 1e-05 True Keras::(1, 160, 160, 2) / NCNN::(1, 160, 160, 2)
Estimated float32 inference memory :: 27 MB

**Comment by azeme1** [comment]
https://www.dropbox.com/sh/8anok3k3jxjj81i/AADWMLad_V0MKs4ySN2mgPPda?dl=0
The conversion result can be found here
model_zoo\variouse\issue_00014

**Comment by wangjing60755** [comment]
Where have you changed? I run keras2ncnn.py , an error will be reported about relu6。Can you update the code？

**Comment by azeme1** [comment]
Pushed to main from dev....
run_test.py contains example of conversion and verification.

**Comment by azeme1** [comment]
Is the problem solved?

**Comment by wangjing60755** [comment]
solved. I get the ncnn model ,which inference well.  thanks！@azeme1

**Comment by azeme1** [comment]
Thanx for the assistance. I close the issue.
